spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
        - id: task-service
          uri: http://task-service:8080
          predicates:
            - Path=/api/tasks/**
        - id: notification-service
          uri: http://notification-service:8082
          predicates:
            - Path=/api/notifications/**

jwt:
  secret: ${JWT_SECRET:miClaveSecretaSuperSeguraDeAlMenos256Bits1234567890}
  expiration: 3600000

server:
  port: 8080