version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  msvc-task:
    build: ./msvc-task
    container_name: task-service
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/taskdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  msvc-user:
    build: ./msvc-user
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

  mongodb:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  msvc-notification:
    build: ./msvc-notification
    container_name: notification-service
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    environment:
      SPRING_APPLICATION_NAME: msvc-notification
      SERVER_PORT: 8082
      SPRING_DATA_MONGODB_URI: mongodb://mongo_db:27017/notificationdb

  gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "8085:8080"   # expone el gateway en tu m√°quina en 8085
    depends_on:
      - msvc-user
      - msvc-task
      - msvc-notification
    environment:
      SPRING_APPLICATION_NAME: msvc-gateway
      SERVER_PORT: 8080
      JWT_SECRET: MiClaveSuperSecreta1234567890

volumes:
  mysql_data:
  postgres_data:
  mongo_data: